# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='birth_year',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='characters',
            name='height',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='characters',
            name='mass',
            field=models.CharField(max_length=8),
        ),
    ]
