# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0002_auto_20160826_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=5)),
                ('method', models.CharField(max_length=4)),
                ('path', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=8)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
