# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0004_characterslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='pic',
            field=models.FileField(default=b'media/no-img.jpg', upload_to=b'media/'),
        ),
    ]
