# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 21:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0005_characters_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterslog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 27, 21, 19, 59, 990987, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 27, 21, 19, 59, 989853, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='characters',
            name='pic',
            field=models.FileField(default=b'no-img.jpg', upload_to=b''),
        ),
    ]
